name: License Check

# Verify Unity license or show setup instructions.
# See: https://game.ci/docs/github/activation

on:
  workflow_dispatch:

jobs:
  license:
    name: Check Unity License
    uses: dyCuong03/unity-build-workflows/.github/workflows/unity-license-check.yml@feature/license-check
    with:
      unity-version: '6000.0.26f1'
    secrets:
      UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
